Strategiga/AdminPage/urls.py
from django.urls import path

from . import views

app_name = 'AdminPage'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('updateuser/<int:pk>', views.UpdateUser, name='update_user'),
    path('swap_strategies/', views.SwapStrategies, name='swap_strategies'),
]

Strategiga/StratBook/urls.py
from django.urls import path

from . import views

app_name = 'StratBook'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('map/add/', views.CreateMapView.as_view(), name="add_map"),
    path('map/<int:pk>/', views.MapDetailView.as_view(), name="map"),
    path('map/<int:pk>/delete/', views.DeleteMapView.as_view(), name="delete_map"),
    path('map/<int:pk>/strat/add/', views.create_strat_view, name="add_strat"),
    path('nadebook/', views.NadeIndexView.as_view(), name='nadebook'),
    path('map/<int:pk>/nades/', views.NadeMapDetailView.as_view(), name='nadeMap'),
    path('nade/<int:pk>/', views.NadeDetailView.as_view(), name="nade"),
    path('nade/<int:pk>/edit', views.NadeUpdateView.as_view(), name="update_nade"),
    path('nade/<int:pk>/delete', views.NadeDeleteView.as_view(), name="delete_nade"),
    path('map/<int:pk>/nades/add', views.NadeCreateView.as_view(), name='add_nade'),
    path('strat/<int:pk>/', views.StrategyDetailView.as_view(), name="strat"),
    path('strat/<int:pk>/edit/', views.update_strat_view, name="update_strat"),
    path('strat/<int:pk>/delete/', views.DeleteStrat.as_view(), name="delete_strat"),
    path('category/add/', views.CreateCategoryView.as_view(), name="add_category"),
    path('category/delete/', views.DeleteCategories, name="delete_categories"),
    path('category/<int:pk>/edit/', views.UpdateCategoryView.as_view(), name="update_category"),
]

Strategiga/Strategiga/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views, settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('', views.index, name='index'),
    path('stratbook/', include('StratBook.urls')),
    path('register/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('adminpage/', include('AdminPage.urls')),
    path('admin/', admin.site.urls),
    ]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Strategiga/AdminPage/models.py
from django.db import models

# Create your models here.
class Admin(models.Model):
    class Meta:
        permissions = (
            ('can_swap_strats', 'Can swap the strategies between two players'),
            ('can_see_hidden_strats', 'Can see hidden strategies'),
        )

Strategiga/AdminPage/views.py
from django.views import generic
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.models import User, Group
from StratBook.models import PlayerOrdering, Map, Category
from StratBook.forms import CategoryForm
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django import template
from django.urls import reverse
from django.db.models import F

# Create your views here.
@method_decorator(permission_required('AdminPage.view_admin', raise_exception=True), name='dispatch')
@method_decorator(permission_required('StratBook.view_category', raise_exception=True), name='dispatch')
@method_decorator(permission_required('StratBook.view_playerordering', raise_exception=True), name='dispatch')
@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = 'AdminPage/index.html'
    context_object_name = 'players'

    def get_queryset(self):
        return User.objects.all().order_by(
                F('playerordering__number').asc(nulls_last=True))

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['maps'] = Map.objects.all().order_by('name')
        context['categories'] = Category.objects.all().order_by('ordering')
        return context

@permission_required('AdminPage.change_admin', raise_exception=True)
@login_required
def UpdateUser(request, pk):
    usr = User.objects.get(pk=pk)
    admin_group = Group.objects.get(name='Admin')
    member_group = Group.objects.get(name='Member')
    if request.POST['ordering'] == '':
        ordering = None
    else:
        ordering = request.POST['ordering']

    try:
        usr.playerordering.number = ordering
    except PlayerOrdering.DoesNotExist:
        PlayerOrdering(player=usr).save()
        usr.playerordering.number = ordering

    if(request.POST.get('is_member')):
        usr.groups.add(member_group)
    else:
        member_group.user_set.remove(usr)

    if(request.POST.get('is_admin')):
        usr.groups.add(admin_group)
    else:
        admin_group.user_set.remove(usr)

    usr.save()
    usr.playerordering.save()
    messages.success(request, str.format("User: {} was updated successfully", usr.username))
    return HttpResponseRedirect(reverse('AdminPage:index'))


@permission_required('AdminPage.change_admin', raise_exception=True)
@permission_required('StratBook.change_strategy', raise_exception=True)
@login_required
def SwapStrategies(request):
    pid1 = request.POST.get('swapPlayer1','')
    pid2 = request.POST.get('swapPlayer2','')
    mapIds = request.POST.get('maps', '')
    mapStrList = []

    if (pid1 and pid2):
        player1 = User.objects.get(pk=pid1)
        player2 = User.objects.get(pk=pid2)

        if mapIds == 'all':
            maps = Map.objects.all()
        else:
            maps = Map.objects.filter(pk=mapIds)

        for _map in maps:
            mapStrList.append(_map.name)
            for strat in _map.strategy_set.all():
                strat.swap_bullets(player1, player2)
        messages.success(request, 
            str.format('Succesfully swapped strats between {0} and {1} on {2}', 
                player1, player2, mapStrList))
    else:
        messages.error(request, 'Can not swap strategies unless two players have been selected')
    return HttpResponseRedirect(reverse('AdminPage:index'))

Strategiga/AdminPage/templates/AdminPage/_add_category_panel.html
<div class="modal fade" id="add-category-panel" tabindex="-1"
        role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Create new category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action={% url 'StratBook:add_category' %}>
        <div class="modal-body">
          <div classs="form-group">
            <label>Name</label>
            <input type="text" name="name" class="form-control">
          </div>
          <div classs="form-group">
            <label>Ordering</label>
            <input type="number" name="ordering" class="form-control">
          </div>
        </div>
        <div class="modal-footer">
          <input type="submit" class="btn btn-success btn-lg btn-block" value="Add category"></input>
        </div>
        {% csrf_token %}
      </form>
    </div>
  </div>
</div>

Strategiga/AdminPage/templates/AdminPage/_categories.html
{% for category in categories %}
<tr>
  <td><input type="checkbox" form="delete-categories" name="delete" value="{{category.id}}"></td>
  <th scope="row">{{category.name}}</th>
  <td>{{category.ordering}}</td>
  <td><a href="#" class="card-link" data-toggle="modal"
                                    data-target="#modal-category-{{category.id}}">
                  <i class="fas fa-cog"></i>
      </a>
  </td>
</tr>

<div class="modal fade" id="modal-category-{{category.id}}" tabindex="-1"
        role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{category.name}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" id="category-{{category.id}}-form" action={% url 'StratBook:update_category' category.id %}>
      {% csrf_token %}
      </form>
      <div class="modal-body">
        <div class="form-group">
          <label>Name</label>
          <input type="text" form="category-{{category.id}}-form" name="name"
            class="form-control" value="{{category.name}}">
        </div>
        <div class="form-group">
            <label>Ordering</label>
            <input type="number" form="category-{{category.id}}-form" name="ordering"
            class="form-control" value="{{category.ordering}}">
        </div>
      </div>
      <div class="modal-footer">
          <input type="submit" form="category-{{category.id}}-form" 
          class="btn btn-primary btn-lg btn-block" value="Save changes"></input>
      </div>
    </div>
  </div>
</div>
{% endfor %}

Strategiga/AdminPage/templates/AdminPage/_swap_panel.html
<a href="#" class="btn btn-lg btn-primary" 
            data-toggle="modal" data-target="#swap-panel">
            <i class="fas fa-users-cog"></i> Swap strategy bullets
</a>

<div class="modal fade" id="swap-panel" tabindex="-1"
        role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Swap strategy bullets</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action={% url 'AdminPage:swap_strategies' %}>
        <div class="modal-body">
          <div class="form-group">
            <label>Player 1</label>
            <select class="form-control" name="swapPlayer1">
              <option value="" selected>--------</option>
              {% for player in players %}
                <option value="{{player.id}}">{{player.username}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <label>Player 2</label>
            <select class="form-control" name="swapPlayer2">
              <option value="" selected>--------</option>
              {% for player in players %}
                <option value="{{player.id}}">{{player.username}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <label>Swap strategy bullets for:</label>
            <select class="form-control" name="maps">
              <option value="all" selected>All Maps</option>
              {% for map in maps %}
                <option value="{{map.id}}">{{map.name}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="modal-footer">
          <input type="submit" class="btn btn-primary btn-lg btn-block" value="Swap bullets"></input>
        </div>
        {% csrf_token %}
      </form>
    </div>
  </div>
</div>

Strategiga/AdminPage/templates/AdminPage/_users.html
{% for player in players %}
<tr>
  <th scope="row">{{player.username}}</th>
  <td>{{player.first_name}}</td>
  <td>{{player.last_name}}</td>
  <td>{{player.playerordering.number}}</td>
  <td><a href="#" class="card-link" data-toggle="modal"
                                    data-target="#modal-{{player.id}}">
                  <i class="fas fa-cog"></i>
      </a>
  </td>
</tr>

<div class="modal fade" id="modal-{{player.id}}" tabindex="-1"
        role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{player.first_name}} '{{player.username}}' {{player.last_name}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action={% url 'AdminPage:update_user' player.id %}>
        <div class="modal-body">
          <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" placeholder="{{player.username}}" disabled>
          </div>
          <div class="form-group">
            <label>Name</label>
            <input type="text" class="form-control" placeholder="{{player.first_name}} {{player.last_name}}" disabled>
          </div>
          <div class="form-group">
            <label>Email</label>
            <input type="text" class="form-control" placeholder="{{player.email}}" disabled>
          </div>
            <div class="form-group">
              <label>Player ordering</label>
              <input type="number" name="ordering" class="form-control" value="{{player.playerordering.number}}">
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <div class="form-check">
                  <input type="checkbox" name="is_member" class="form-check-input" {{player|member_checked}}>
                  <label class="form-check-label">Member</label>
                </div>
              </div>
              <div class="form-group col-md-6">
                <div class="form-check">
                  <input type="checkbox" name="is_admin" class="form-check-input" {{player|admin_checked}}>
                  <label class="form-check-label">Admin</label>
                </div>
              </div>
            </div>
        </div>
        <div class="modal-footer">
            <input type="submit" class="btn btn-primary btn-lg btn-block" value="Save changes"></input>
        </div>
        {% csrf_token %}
      </form>
    </div>
  </div>
</div>
{% endfor %}

Strategiga/AdminPage/templates/AdminPage/index.html
{% extends "base.html" %}

{% block title %}Admin Page{% endblock %}
{% load adminmodule %}
{% load static %}

{% block content %}
<div class="card">
  <h3 class="card-header bg-secondary text-light">Users</h3>
  <div class="card-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">User</th>
          <th scope="col">Firstname</th>
          <th scope="col">Lastname</th>
          <th scope="col">Ordering</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% include 'AdminPage/_users.html' %}
      </tbody>
    </table>
    {% include 'AdminPage/_swap_panel.html' %}
  </div>
</div>
<div class="card mt-4">
  <h3 class="card-header bg-secondary text-light">Categories</h3>
  <div class="card-body">
    <form method="post" id="delete-categories" action={% url 'StratBook:delete_categories' %}>
      {% csrf_token %}
    </form>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">Name</th>
          <th scope="col">Ordering</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% include 'AdminPage/_categories.html' %}
      </tbody>
    </table>
    <a href="#" class="btn btn-lg btn-success" 
          data-toggle="modal" data-target="#add-category-panel">
          <i class="fas fa-pen"></i> Create new category
    </a>
    <button type="submit" class="btn btn-lg btn-danger ml-4" form="delete-categories"
            onclick="return confirm('Are you sure you want to delete the marked categories?')">
        <i class="fas fa-trash"></i> Delete marked categories
    </button>
    {% csrf_token %}
    {% include 'AdminPage/_add_category_panel.html' %}
  </div>
</div>
<script src={% static 'AdminPage/js/adminPage.js' %}></script>
{% endblock %}