Strategiga/AdminPage/urls.py
from django.urls import path

from . import views

app_name = 'AdminPage'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('updateuser/<int:pk>', views.UpdateUser, name='update_user'),
    path('swap_strategies/', views.SwapStrategies, name='swap_strategies'),
]

Strategiga/StratBook/urls.py
from django.urls import path

from . import views

app_name = 'StratBook'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('map/add/', views.CreateMapView.as_view(), name="add_map"),
    path('map/<int:pk>/', views.MapDetailView.as_view(), name="map"),
    path('map/<int:pk>/delete/', views.DeleteMapView.as_view(), name="delete_map"),
    path('map/<int:pk>/strat/add/', views.create_strat_view, name="add_strat"),
    path('nadebook/', views.NadeIndexView.as_view(), name='nadebook'),
    path('map/<int:pk>/nades/', views.NadeMapDetailView.as_view(), name='nadeMap'),
    path('nade/<int:pk>/', views.NadeDetailView.as_view(), name="nade"),
    path('nade/<int:pk>/edit', views.NadeUpdateView.as_view(), name="update_nade"),
    path('nade/<int:pk>/delete', views.NadeDeleteView.as_view(), name="delete_nade"),
    path('map/<int:pk>/nades/add', views.NadeCreateView.as_view(), name='add_nade'),
    path('strat/<int:pk>/', views.StrategyDetailView.as_view(), name="strat"),
    path('strat/<int:pk>/edit/', views.update_strat_view, name="update_strat"),
    path('strat/<int:pk>/delete/', views.DeleteStrat.as_view(), name="delete_strat"),
    path('category/add/', views.CreateCategoryView.as_view(), name="add_category"),
    path('category/delete/', views.DeleteCategories, name="delete_categories"),
    path('category/<int:pk>/edit/', views.UpdateCategoryView.as_view(), name="update_category"),
]

Strategiga/Strategiga/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views, settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('', views.index, name='index'),
    path('stratbook/', include('StratBook.urls')),
    path('register/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('adminpage/', include('AdminPage.urls')),
    path('admin/', admin.site.urls),
    ]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Strategiga/AdminPage/models.py
from django.db import models

# Create your models here.
class Admin(models.Model):
    class Meta:
        permissions = (
            ('can_swap_strats', 'Can swap the strategies between two players'),
            ('can_see_hidden_strats', 'Can see hidden strategies'),
        )

Strategiga/templates/base.html
{% load static %}
<html>
  <head>
    <link rel="stylesheet" type="text/css" href={% static 'Strategiga/css/style.css' %}>
    <link rel="shortcut icon" type="image/png" href="{% static 'Strategiga/images/favicon.png' %}?v=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
      integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
      crossorigin="anonymous">
    <link rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous">
      </script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
              integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
              crossorigin="anonymous">
      </script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
              integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
              crossorigin="anonymous">
      </script>
    <title>
      {% block title %}{% endblock %}
    </title>
  </head>
  <body>
    {% include "navbar.html" %}
    {% include "messages.html" %}
    <div class="container-fluid mt-4 content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

Strategiga/templates/index.html
{% extends "base.html" %}

{% block title %}Strategiga{% endblock %}

{% block content %}
  <div class="jumbotron">
    <h1 class="display-4">Front page LOL</h1>
    <hr class="my-4">
    <p>Completely unnecessary, move along!</p>
    {% if not user.is_authenticated %}
    <p class="lead">
      <a class="btn btn-primary btn-lg" href={% url 'login' %}>Log In</a>
      <a class="btn btn-success btn-lg" href={% url 'signup' %}>Register</a>
    </p>
    {% endif %}
  </div>
{% endblock %}

Strategiga/templates/messages.html
{% if messages %}
<div class="messages">
	{% for message in messages %}
		{% if message.tags %}
			<div class="alert alert-{{ message.tags }}">
				<div>{{ message }}</div>
			</div>
		{% endif %}
	{% endfor %}
</div>
{% endif %}

Strategiga/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" href={% url 'index' %}>Strategiga</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04"
    aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample04">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href={% url 'StratBook:index' %}>Stratbook</a>
      </li>
      <li class="nav-item">
              <a class="nav-link" href={% url 'StratBook:nadebook' %}>Nadebook</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <div class="welcomer"> Welcome {{user.username}}</div>
          </li>
          {% if perms.AdminPage.view_admin %}
            <li class="nav-item">
              <a class="nav-link" href={% url 'AdminPage:index' %}>Admin</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href={% url 'password_change' %}>Change Password</a>
          </li>
          <li class="divider-vertical"></li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'logout' %}>Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href={% url 'login' %}>Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'signup' %}>Register</a>
          </li>
        {% endif %}
    </ul>
  </div>
</nav>