Strategiga/AdminPage/urls.py
from django.urls import path

from . import views

app_name = 'AdminPage'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('updateuser/<int:pk>', views.UpdateUser, name='update_user'),
    path('swap_strategies/', views.SwapStrategies, name='swap_strategies'),
]

Strategiga/StratBook/urls.py
from django.urls import path

from . import views

app_name = 'StratBook'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('map/add/', views.CreateMapView.as_view(), name="add_map"),
    path('map/<int:pk>/', views.MapDetailView.as_view(), name="map"),
    path('map/<int:pk>/delete/', views.DeleteMapView.as_view(), name="delete_map"),
    path('map/<int:pk>/strat/add/', views.create_strat_view, name="add_strat"),
    path('nadebook/', views.NadeIndexView.as_view(), name='nadebook'),
    path('map/<int:pk>/nades/', views.NadeMapDetailView.as_view(), name='nadeMap'),
    path('nade/<int:pk>/', views.NadeDetailView.as_view(), name="nade"),
    path('nade/<int:pk>/edit', views.NadeUpdateView.as_view(), name="update_nade"),
    path('nade/<int:pk>/delete', views.NadeDeleteView.as_view(), name="delete_nade"),
    path('map/<int:pk>/nades/add', views.NadeCreateView.as_view(), name='add_nade'),
    path('strat/<int:pk>/', views.StrategyDetailView.as_view(), name="strat"),
    path('strat/<int:pk>/edit/', views.update_strat_view, name="update_strat"),
    path('strat/<int:pk>/delete/', views.DeleteStrat.as_view(), name="delete_strat"),
    path('category/add/', views.CreateCategoryView.as_view(), name="add_category"),
    path('category/delete/', views.DeleteCategories, name="delete_categories"),
    path('category/<int:pk>/edit/', views.UpdateCategoryView.as_view(), name="update_category"),
]

Strategiga/Strategiga/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views, settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('', views.index, name='index'),
    path('stratbook/', include('StratBook.urls')),
    path('register/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('adminpage/', include('AdminPage.urls')),
    path('admin/', admin.site.urls),
    ]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Strategiga/StratBook/models.py
from django.db import models
from django.db.models import F
from django.utils import timezone
from django.utils.encoding import iri_to_uri
from django.contrib.auth import get_user_model
from itertools import chain
import re

def map_directory_path(instance, filename):
    iri = 'maps/{0}_{1}'.format(timezone.now(), filename)
    return iri_to_uri(iri)

# Create your models here.
class Map(models.Model):
    name = models.CharField(max_length=50)
    active_duty = models.BooleanField(default=True)
    img = models.ImageField(upload_to=map_directory_path, blank=True, null=True)

    def __str__(self):
        return self.name

    def ct_strategies(self):
        return self.strategy_set.filter(team='CT').order_by(F('category__ordering').asc(nulls_last=True), 'name')
    def t_strategies(self):
        return self.strategy_set.filter(team='T').order_by(F('category__ordering').asc(nulls_last=True), 'name')
    def smokes(self):
        return self.nade_set.filter(nade_type='S').order_by('name')
    def molotovs(self):
        return self.nade_set.filter(nade_type='M').order_by('name')
    def flashes(self):
        return self.nade_set.filter(nade_type='F').order_by('name')
    def HEs(self):
        return self.nade_set.filter(nade_type='H').order_by('name')

class Category(models.Model):
    name = models.CharField(max_length=50)
    ordering = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

class Strategy(models.Model):
    TEAM_CHOICES = [
        ('T', 'Terrorist'),
        ('CT', 'Counter-Terrorist')
    ]
    map_name = models.ForeignKey(Map, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    team = models.CharField(max_length=2, choices=TEAM_CHOICES)
    added_date = models.DateTimeField('date added', default=timezone.now)
    updated_date = models.DateTimeField('date added', default=timezone.now)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    is_hidden = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def team_text(self):
        for (t, name) in self.TEAM_CHOICES:
            if self.team == t:
                return name

    def is_new(self):
        time_between_insertion =  timezone.now() - self.updated_date
        return time_between_insertion.days < 7

    def swap_bullets(self, player1, player2):
        p1_bullets = list(player1.bullet_set.filter(strategy_id=self.id))
        p2_bullets = list(player2.bullet_set.filter(strategy_id=self.id))
        for bullet in p1_bullets:
            bullet.player = player2
            bullet.save()
        for bullet in p2_bullets:
            bullet.player = player1
            bullet.save()

    def bullets(self):
        # whether or not there are any bullets with players using orderings
        sort_by_player_ordering = len([True for bullet
            in self.bullet_set.all()
            if bullet.player and bullet.player.playerordering.number is not None]) > 0
        
        if (sort_by_player_ordering):
            return self.bullet_set.order_by(
                F('player__playerordering__number').asc(nulls_last=True), 'id')

        return self.bullet_set.order_by('id')

def nade_directory_path(instance, filename):
    iri = 'nades/{0}_{1}'.format(instance.map_name.id, filename)
    return iri_to_uri(iri)

class Nade(models.Model):
    NADE_TYPE_CHOICES = [
        ('S', 'Smoke'),
        ('M', 'Molotov'),
        ('F', 'Flash'),
        ('H', 'HE Grenade')
    ]
    name = models.CharField(max_length=50)
    map_name = models.ForeignKey(Map, on_delete=models.CASCADE, null=True)
    nade_type = models.CharField(max_length=1, choices=NADE_TYPE_CHOICES)
    description = models.TextField(blank=True)
    setup_img_link = models.URLField(blank=True)
    setup_img = models.ImageField(upload_to=nade_directory_path, blank=True, null=True)
    img_link = models.URLField(blank=True)
    img = models.ImageField(upload_to=nade_directory_path, blank=True, null=True)

    def __str__(self):
        return self.name

    def get_name(self):
        return self.name

    def get_setup_image_url(self):
        if (self.setup_img):
            return self.setup_img.url
        if (self.setup_img_link):
            return self.setup_img_link
        return ''

    def get_image_url(self):
        if (self.img):
            return self.img.url
        if (self.img_link):
            return self.img_link
        return ''

    def type_text(self):
        for (t, name) in self.NADE_TYPE_CHOICES:
            if self.nade_type == t:
                return name

    def has_setup(self):
        if (self.setup_img):
            return True
        elif (self.setup_img_link):
            return True
        else:
            return False

class Bullet(models.Model):
    text = models.CharField(max_length=200, blank=True)
    strategy = models.ForeignKey(Strategy, on_delete=models.CASCADE)
    player = models.ForeignKey(get_user_model(),
            on_delete=models.SET_NULL, blank=True, null=True)
    nade = models.ForeignKey(Nade, on_delete=models.SET_NULL, blank=True, null=True)

    def delete_if_empty(self):
        text = self.text.strip()
        if ((text == '@player' or not text)
                and not self.nade and not self.player):
            self.delete()

    def replace_player_text(self):
        if self.player:
            name = self.player.username

            return self.text.replace("@player", name)
        else:
            return self.text

class PlayerOrdering(models.Model):
    number = models.IntegerField(blank=True, null=True)
    player = models.OneToOneField(get_user_model(),
            on_delete=models.SET_NULL, blank=True, null=True)

Strategiga/StratBook/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Map, Strategy, Nade, Bullet, Category

class MapForm(forms.ModelForm):
    name = forms.CharField(max_length=50)
    active_duty = forms.BooleanField(initial=True, required=False)
    img = forms.ImageField(required=False)

    class Meta:
        model = Map
        fields = ('name', 'active_duty', 'img')

class StratForm(forms.ModelForm):
    map_name = forms.ModelChoiceField(queryset=Map.objects.all(), required=False, widget=forms.HiddenInput())
    name = forms.CharField(max_length=200)
    team = forms.ChoiceField(choices=Strategy.TEAM_CHOICES)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False)
    is_hidden = forms.BooleanField(required=False)

    name.widget.attrs.update({'class': 'form-control'})
    team.widget.attrs.update({'class': 'form-control'})
    category.widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Strategy
        fields = ('map_name', 'name', 'team', 'category', 'is_hidden')

class NadeForm(forms.ModelForm):
    map_name = forms.ModelChoiceField(queryset=Map.objects.all(), required=False, widget=forms.HiddenInput())
    name = forms.CharField(max_length=200)
    description = forms.CharField(widget=forms.Textarea(), required=False)
    nade_type = forms.ChoiceField(choices=Nade.NADE_TYPE_CHOICES)
    setup_img = forms.ImageField(required=False)
    setup_img_link = forms.URLField(required=False)
    img = forms.ImageField(required=False)
    img_link = forms.URLField(required=False)

    class Meta:
        model = Nade
        fields = ('map_name', 'name', 'description', 'nade_type',
            'setup_img', 'setup_img_link', 'img', 'img_link')

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=200)
    ordering = forms.IntegerField(required=False)

    class Meta:
        model = Category
        fields = ('name', 'ordering')

Strategiga/AdminPage/views.py
from django.views import generic
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.models import User, Group
from StratBook.models import PlayerOrdering, Map, Category
from StratBook.forms import CategoryForm
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django import template
from django.urls import reverse
from django.db.models import F

# Create your views here.
@method_decorator(permission_required('AdminPage.view_admin', raise_exception=True), name='dispatch')
@method_decorator(permission_required('StratBook.view_category', raise_exception=True), name='dispatch')
@method_decorator(permission_required('StratBook.view_playerordering', raise_exception=True), name='dispatch')
@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = 'AdminPage/index.html'
    context_object_name = 'players'

    def get_queryset(self):
        return User.objects.all().order_by(
                F('playerordering__number').asc(nulls_last=True))

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['maps'] = Map.objects.all().order_by('name')
        context['categories'] = Category.objects.all().order_by('ordering')
        return context

@permission_required('AdminPage.change_admin', raise_exception=True)
@login_required
def UpdateUser(request, pk):
    usr = User.objects.get(pk=pk)
    admin_group = Group.objects.get(name='Admin')
    member_group = Group.objects.get(name='Member')
    if request.POST['ordering'] == '':
        ordering = None
    else:
        ordering = request.POST['ordering']

    try:
        usr.playerordering.number = ordering
    except PlayerOrdering.DoesNotExist:
        PlayerOrdering(player=usr).save()
        usr.playerordering.number = ordering

    if(request.POST.get('is_member')):
        usr.groups.add(member_group)
    else:
        member_group.user_set.remove(usr)

    if(request.POST.get('is_admin')):
        usr.groups.add(admin_group)
    else:
        admin_group.user_set.remove(usr)

    usr.save()
    usr.playerordering.save()
    messages.success(request, str.format("User: {} was updated successfully", usr.username))
    return HttpResponseRedirect(reverse('AdminPage:index'))


@permission_required('AdminPage.change_admin', raise_exception=True)
@permission_required('StratBook.change_strategy', raise_exception=True)
@login_required
def SwapStrategies(request):
    pid1 = request.POST.get('swapPlayer1','')
    pid2 = request.POST.get('swapPlayer2','')
    mapIds = request.POST.get('maps', '')
    mapStrList = []

    if (pid1 and pid2):
        player1 = User.objects.get(pk=pid1)
        player2 = User.objects.get(pk=pid2)

        if mapIds == 'all':
            maps = Map.objects.all()
        else:
            maps = Map.objects.filter(pk=mapIds)

        for _map in maps:
            mapStrList.append(_map.name)
            for strat in _map.strategy_set.all():
                strat.swap_bullets(player1, player2)
        messages.success(request, 
            str.format('Succesfully swapped strats between {0} and {1} on {2}', 
                player1, player2, mapStrList))
    else:
        messages.error(request, 'Can not swap strategies unless two players have been selected')
    return HttpResponseRedirect(reverse('AdminPage:index'))

Strategiga/StratBook/templates/StratBook/_mini_nav_nade.html
<nav class="navbar navbar-expand-sm">
  <ul class="navbar-nav mr-auto">
    <li class="nav-link">
            <a class="btn btn-outline-primary btn-light" 
                    href={% url 'StratBook:nadebook' %}>&laquo Map Overview</a>
    </li>
    {% if nade %}
    <li class="nav-link">
      <a class="btn btn-outline-primary btn-light" 
              href={% url 'StratBook:nadeMap' nade.map_name.id %}>&laquo; {{nade.map_name.name}}
      </a>
    </li>
    {% endif %}
  </ul>
</nav>

Strategiga/StratBook/templates/StratBook/_nade_card.html
<a class="card-link" href={% url 'StratBook:nade' nade.id %}>
  <div class="card text-dark nade-card">
    <img class="card-img-top nadepic" src="{{ nade.get_image_url }}">
    <div class="card-body">
      <p class="card-text">{{nade.name}}</p>
    </div>
  </div>
</a>

Strategiga/StratBook/templates/StratBook/category_add.html
{% extends "base.html" %}

{% block title %}Add Category{% endblock %}

{% load crispy_forms_tags %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mt-2">Add Category</button>
  </form>
{% endblock %}

Strategiga/StratBook/templates/StratBook/category_edit.html
{% extends "base.html" %}

{% block title %}Edit Category{% endblock %}

{% load crispy_forms_tags %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mt-2">Save changes</button>
  </form>
{% endblock %}

Strategiga/StratBook/templates/StratBook/index.html
{% extends "base.html" %}

{% block title %}Map Overview - Stratbook{% endblock %}

{% load static %}
{% block content %}
  <div class="custom-control custom-checkbox mb-4">
    <input type="checkbox" class="custom-control-input" id="activeDutyCheck" checked>
    <label class="custom-control-label" for="activeDutyCheck">Only show active duty</label>
  </div>
  {% if perms.StratBook.view_map %}
    <h3>Active Maps</h1>
    <hr>
    {% if map_list %}
      <div class="row mb-4">
      {% for map in map_list %}
    	  <div class="col-sm-3">
	        <a class="card-link" href={% url 'StratBook:map' map.id %}>
	          <div class="card">
              {% if map.img %}
              <img src={{ map.img.url }} class="card-img-top">
              {% endif %}
	      		  <div class="card-body">
	      			  <p class="card-text">{{ map.name }}</p>
	      		  </div>
	      	  </div>
	    	  </a>
	      </div>
        {% if forloop.counter|divisibleby:4 %}
        </div>
        <div class="row mb-4">
        {% endif %}
      {% endfor %}
      </div>
    {% else %}
      <p>No active maps available.</p>
    {% endif %}
    <div id="inactive_maps" style="display:none">
      <hr>
      <h3 class="mt-4">Inactive Maps</h3>
      <hr>
      {% if inactive_map_list %}
        <div class="row mb-4">
        {% for map in inactive_map_list %}
      	  <div class="col-sm-3">
  	        <a class="card-link" href={% url 'StratBook:map' map.id %}>
  	    	    <div class="card">
                {% if map.img %}
                <img src={{ map.img.url }} class="card-img-top">
                {% endif %}
  	      	    <div class="card-body">
  	              <p class="card-text">{{ map.name }}</p>
  	      	    </div>
  	          </div>
  	        </a>
  	      </div>
        {% if forloop.counter|divisibleby:4 %}
        </div>
        <div class="row mb-4">
        {% endif %}
        {% endfor %}
        </div>
      {% else %}
        <p>No Inactive maps available.</p>
      {% endif %}
    </div>
  {% else %}
    <p>Your user does not have access to any maps</p>
  {% endif %}
  {% if perms.StratBook.add_map %}
    <a href={% url 'StratBook:add_map' %} class="btn btn-success mb-4">+ Add Map</a>
  {% endif %}
  <script src={% static 'StratBook/js/index.js' %}>
  </script>
{% endblock %}

Strategiga/StratBook/templates/StratBook/map_add.html
{% extends "base.html" %}

{% block title %}Add Map{% endblock %}

{% load crispy_forms_tags %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mt-2">Add Map</button>
  </form>
{% endblock %}

Strategiga/StratBook/templates/StratBook/map_detail_nade.html
{% extends "base.html" %}

{% block title %}{{map.name}} Nades{% endblock %}

{% block content %}
{% load static %}
{% include 'StratBook/_mini_nav_nade.html' %}
<hr>

{% if map.smokes %}
<h2>Smokes</h2>
<hr>
<div class="row mb-4">
  {% for nade in map.smokes %}
      <div class="col-sm-3">
        {% include 'StratBook/_nade_card.html' %}
      </div>
  {% if forloop.counter|divisibleby:4 %}
    </div>
    <div class="row mb-4">
  {% endif %}
  {% endfor %}
  </div>
{% endif %}

{% if map.molotovs %}
<h2>Molotovs</h2>
<hr>
<div class="row mb-4">
  {% for nade in map.molotovs %}
      <div class="col-sm-3">
        {% include 'StratBook/_nade_card.html' %}
      </div>
  {% if forloop.counter|divisibleby:4 %}
    </div>
    <div class="row mb-4">
  {% endif %}
  {% endfor %}
  </div>
{% endif %}

{% if map.flashes %}
<h2>Flashes</h2>
<hr>
<div class="row mb-4">
  {% for nade in map.flashes %}
      <div class="col-sm-3">
        {% include 'StratBook/_nade_card.html' %}
      </div>
  {% if forloop.counter|divisibleby:4 %}
    </div>
    <div class="row mb-4">
  {% endif %}
  {% endfor %}
  </div>
{% endif %}

{% if map.HEs %}
<h2>HE-grenades</h2>
<hr>
<div class="row mb-4">
  {% for nade in map.HEs %}
    <div class="col-sm-3">
      {% include 'StratBook/_nade_card.html' %}
    </div>
  {% if forloop.counter|divisibleby:4 %}
    </div>
    <div class="row mb-4">
  {% endif %}
  {% endfor %}
  </div>
{% endif %}

<div class="row mb-4">
  <div class="col">
{% if perms.StratBook.add_nade %}
  <a href={% url 'StratBook:add_nade' map.id %} class="btn btn-success">+ Add Nade</a>
{% endif %}

{% if perms.StratBook.delete_map %}
  <a href={% url 'StratBook:delete_map' map.id %} class="btn btn-danger">- Delete Map</a>
{% endif %}
  </div>
</div>
<script src={% static 'StratBook/js/map_detail_nade.js' %}></script>
{% endblock %}

Strategiga/StratBook/templates/StratBook/map_detail_v2.html
{% extends "base.html" %}

{% block title %}{{map.name}} Strats{% endblock %}

{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'StratBook/css/strat_detail.css' %}?v=1">
<script src={% static 'StratBook/js/strat_detail.js' %}></script>

{% include 'StratBook/_mini_nav.html' %}
<hr>

<div class="row">
  <div class="col-md-9">
    <div class="strats">
      {% if not map.strategy_set.all %}
        <p><small class="text-muted"> No strategies available</small></p>
      {% endif %}

      {% for strat in map.ct_strategies %}
        {% include 'StratBook/_strat_card.html' %}
      {% endfor %}

      {% for strat in map.t_strategies %}
        {% include 'StratBook/_strat_card.html' %}
      {% endfor %}

    </div>
  </div>

  <div class="col-md-3">
    <div class="sticky-top">
      <h3>{{map.name}}</h3> 
      <hr>
      <div class="custom-control custom-checkbox mb-4">
        <input id="egoCheck" type="checkbox" class="custom-control-input">
        <label class="custom-control-label" for="egoCheck">Ego Mode</label>
      </div>
      
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h5 class="card-title">CT Strategies</h5>
        </div>
        <div class="card-body">
          <p class="card-text">
          {% if not map.ct_strategies %}
            <p><small class="text-muted">No CT Strategies available</small></p>
          {% else %}
            {% for strat in map.ct_strategies %}
              {% if not forloop.first %}
                <hr>
              {% endif %}
              <a class="{{strat.team}}-link" href="#strat-{{strat.id}}">
                {{strat.name}}
              </a>
            {% endfor %}
          {% endif %}
          </p>
        </div>
      </div>
      
      <div class="card mt-4">
        <div class="card-header bg-danger text-white">
          <h5 class="card-title">T Strategies</h5>
        </div>
        <div class="card-body">
          <p class="card-text">
          {% if not map.t_strategies %}
            <p><small class="text-muted">No T Strategies available</small></p>
          {% else %}
            {% for strat in map.t_strategies %}
              {% if not forloop.first %}
                <hr>
              {% endif %}
              <a class="{{strat.team}}-link" href="#strat-{{strat.id}}">
                {{strat.name}}
              </a>
            {% endfor %}
          {% endif %}
          </p>
        </div>
      </div>

      <div class="row">
      {% if perms.StratBook.add_strategy %}
        <div class="col">
          <a href={% url 'StratBook:add_strat' map.id %} class="btn-block btn-lg mt-4 mb-4 btn-success">
            <div class="ml-2">+ Add Strategy</div>
          </a>
        </div>
        {% endif %}
        {% if perms.StratBook.delete_map %}
        <div class="col">
          <a href={% url 'StratBook:delete_map' map.id %} 
                 class="btn-block btn-lg mt-4 mb-4 btn-danger">
            <div class="ml-2">- Delete Map</div>
          </a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

Strategiga/StratBook/templates/StratBook/nade_detail.html
{% extends "base.html" %}

{% block title %}{{nade.type_text}}: {{nade.name}}{% endblock %}

{% load static %}
{% block content %}
{% include 'StratBook/_mini_nav_nade.html' %}
<hr>
<div class="row">
  <div class="col-sm-8">


    <div id="nades" class="carousel slide mb-4" data-interval="false">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="{{nade.get_image_url}}" alt="Nade">
        </div>
        {% if nade.has_setup %}
        <div class="carousel-item">
                <img class="d-block w-100" src="{{nade.get_setup_image_url}}" alt="Setup">
        </div>
      </div>
      <a class="carousel-control-prev" href="#nades"
              role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#nades"
              role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
        {% else %}
      </div>
        {% endif %}
    </div>
  </div>
  <div class="col-sm-4">
    <div class="card bg-light">
      <div class="card-body">
        <h3 class="card-title">{{nade.name}}</h3>
        <hr>
        <p class="card-text">
          <p>
          {% if nade.description %}
            {{nade.description|linebreaks}}</p>
          {% else %}
            <small class="text-muted">No description available</small>
          {% endif %}
            <hr>
            <p><small class="text-muted">Included in:</small></p>
            {% for bullet in nade.bullet_set.all %}
            <a class="btn 
                    {% if bullet.strategy.team == 'T' %}
                      btn-outline-danger
                    {% else %}
                      btn-outline-primary
                    {% endif %}
                    " href={% url 'StratBook:strat' bullet.strategy.id %}>
                    {{bullet.strategy}}
            </a>
            {% endfor %}
          </p>
        </p>
      </div>
    </div>
    {% if perms.StratBook.change_nade %}
      <a class="btn btn-primary mt-4" href={% url 'StratBook:update_nade' nade.id %}>Edit</a>
    {% endif %}
    {% if perms.StratBook.delete_nade %}
      <a class="btn btn-danger mt-4" href={% url 'StratBook:delete_nade' nade.id %}>Delete</a>
    {% endif %}
  </div>
</div>
{% endblock %}

Strategiga/StratBook/templates/StratBook/strat_detail.html
{% extends "base.html" %}

{% block title %}Strat: {{strat.name}}{% endblock %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href={% static 'StratBook/css/strat_detail.css' %}>
{% include 'StratBook/_mini_nav.html' %}
<hr>
<div class="row">
  <div class="col-9">
    <div class="card bg-light mt-4">
      <div class="card-body">
        <div class="row">
          <div class="col-md-10">
            <h1 class="card-title">{{strat.name}}</h1>
          </div>
          <div class="col-md-2">
            <div class="custom-control custom-checkbox mb-4">
              <input id="egoCheck" type="checkbox" class="custom-control-input">
              <label class="custom-control-label" for="egoCheck">Ego Mode</label>
            </div>
          </div>
        </div>
        <hr>
        <p class="card-text">
          <div id="bullets">
            {% if not strat.bullet_set.all %}
              <p class="text-muted">
                <small>No description available for this strategy</small>
              </p>
            {% else %}
              {% for bullet in strat.bullets %}
                {% include 'StratBook/_bullet_card.html' %}
              {% endfor %}
            {% endif %}
          </div>
          <p class="team mt-4">Side: {{strat.team_text}}</p>
          <p class="team mt-4">Category: {{strat.category}}</p>
          <p class="date text-muted">
            <small>Date added: {{strat.added_date}}</small>
          </p>
        </p>
      </div>
    </div>
    {% if perms.StratBook.change_strategy %}
      <a class="btn btn-primary mb-4 mt-4" href={% url 'StratBook:update_strat' strat.id %}>Edit</a>
    {% endif %}
    {% if perms.StratBook.delete_strategy %}
      <a class="btn btn-danger mb-4 mt-4" href={% url 'StratBook:delete_strat' strat.id %}>Delete</a>
    {% endif %}
  </div>
  <div class="col-3 mt-4 bg-light">
    {% include 'StratBook/_detail_sidebar.html' %}
  </div>
</div>

<script src={% static 'StratBook/js/strat_detail.js' %}></script>
{% endblock %}